const data = {
  portfolios: [
    {
      title: "Job in Netcentric",
      company: "Netcentric",
      companyWebsite: "www.google.com",
      location: "Spain, Barcelona",
      jobTitle: "Engineer",
      description: "Doing something, programing....",
      startDate: "01/01/2014",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2016",
    },
    {
      title: "Job in Siemens",
      company: "Siemens",
      companyWebsite: "www.google.com",
      location: "Slovakia, Kosice",
      jobTitle: "Software Engineer",
      description: "Responsoble for parsing framework for JSON medical data.",
      startDate: "01/01/2011",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2013",
    },
    {
      title: "Work in USA",
      company: "WhoKnows",
      companyWebsite: "www.google.com",
      location: "USA, Montana",
      jobTitle: "Housekeeping",
      description: "So much responsibility....Overloaaaaaad",
      startDate: "01/01/2010",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2011",
    },
    {
      title: "Job in Netcentric",
      company: "Netcentric",
      companyWebsite: "www.google.com",
      location: "Spain, Barcelona",
      jobTitle: "Engineer",
      description: "Doing something, programing....",
      startDate: "01/01/2014",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2016",
    },
    {
      title: "Job in Siemens",
      company: "Siemens",
      companyWebsite: "www.google.com",
      location: "Slovakia, Kosice",
      jobTitle: "Software Engineer",
      description: "Responsoble for parsing framework for JSON medical data.",
      startDate: "01/01/2011",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2013",
    },
    {
      title: "Work in USA",
      company: "WhoKnows",
      companyWebsite: "www.google.com",
      location: "USA, Montana",
      jobTitle: "Housekeeping",
      description: "So much responsibility....Overloaaaaaad",
      startDate: "01/01/2010",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2011",
    },
    {
      title: "Job in Netcentric",
      company: "Netcentric",
      companyWebsite: "www.google.com",
      location: "Spain, Barcelona",
      jobTitle: "Engineer",
      description: "Doing something, programing....",
      startDate: "01/01/2014",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2016",
    },
    {
      title: "Job in Siemens",
      company: "Siemens",
      companyWebsite: "www.google.com",
      location: "Slovakia, Kosice",
      jobTitle: "Software Engineer",
      description: "Responsoble for parsing framework for JSON medical data.",
      startDate: "01/01/2011",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2013",
    },
    {
      title: "Work in USA",
      company: "WhoKnows",
      companyWebsite: "www.google.com",
      location: "USA, Montana",
      jobTitle: "Housekeeping",
      description: "So much responsibility....Overloaaaaaad",
      startDate: "01/01/2010",
      userId: 'google-oauth2|117001720419944847142',
      endDate: "01/01/2011",
    },
  ],
  blogs: [
    {
      slug: 'my-first-blog',
      title: 'My First Blog',
      subTitle: 'It was chilly winter day...',
      content: '<p>Some very nice content</p>',
      userId: 'google-oauth2|117001720419944847142',
      status: 'published'
    },
    {
      slug: 'my-second-blog',
      title: 'My Second Blog',
      subTitle: 'It was hot summer day...',
      content: '<p>Some very nice content</p>',
      userId: 'google-oauth2|117001720419944847142',
      status: 'published'
    },
    {
      slug: 'my-third-blog',
      title: 'My Third Blog',
      subTitle: 'It was rainy spring day...',
      content: '<p>Some very nice content</p>',
      userId: 'google-oauth2|117001720419944847142',
      status: 'published'
    },
    {
      slug: 'my-forth-blog',
      title: 'My Forth Blog',
      subTitle: 'It was chilly winter day...',
      content: '<p>Some very nice content</p>',
      userId: 'google-oauth2|117001720419944847142',
      status: 'published'
    },
    {
      slug: 'my-fifth-blog',
      title: 'My Fifth Blog',
      subTitle: 'It was hot summer day...',
      content: '<p>Some very nice content</p>',
      userId: 'google-oauth2|117001720419944847142',
      status: 'published'
    },
    {
      slug: 'my-sixth-blog',
      title: 'My Sixth Blog',
      subTitle: 'It was rainy spring day...',
      content: '<p>Some very nice content</p>',
      userId: 'google-oauth2|117001720419944847142',
      status: 'published'
    }
  ]
};

module.exports = data;
